import 'package:flutter/material.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedsystembarswidget/generated/GeneratedStatusBarWidget23.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedsystembarswidget/generated/GeneratedHomeBarWidget25.dart';

/* Frame System Bars
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSystemBarsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 142.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedStatusBarWidget23(),
            ),
            Positioned(
              left: 0.0,
              top: 108.0,
              right: null,
              bottom: null,
              width: 134.0,
              height: 34.0,
              child: GeneratedHomeBarWidget25(),
            )
          ]),
    ));
  }
}
