import 'package:flutter/material.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedresultswidget/generated/GeneratedFrame6Widget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedresultswidget/generated/GeneratedStatusBarWidget8.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedresultswidget/generated/GeneratedHomeBarWidget9.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedresultswidget/generated/GeneratedCardsWidget1.dart';

/* Frame Results
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedResultsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBarWidget8(),
              ),
              Positioned(
                left: 121.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 34.0,
                child: GeneratedHomeBarWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 132.0,
                child: GeneratedFrame6Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 192.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 610.0,
                child: GeneratedCardsWidget1(),
              )
            ]),
      ),
    ));
  }
}
