import 'package:flutter/material.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedyourcourseswidget/generated/GeneratedHomeBarWidget14.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedyourcourseswidget/generated/GeneratedCardsWidget2.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedyourcourseswidget/generated/GeneratedTabBar3ItemWidget1.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedyourcourseswidget/generated/GeneratedStatusBarWidget13.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedyourcourseswidget/generated/GeneratedHeadersWidget5.dart';

/* Frame Your Courses
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedYourCoursesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 923.0,
                child: GeneratedCardsWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBarWidget13(),
              ),
              Positioned(
                left: 121.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 34.0,
                child: GeneratedHomeBarWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 40.0,
                child: GeneratedHeadersWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 714.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 98.0,
                child: GeneratedTabBar3ItemWidget1(),
              )
            ]),
      ),
    ));
  }
}
