import 'package:flutter/material.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedfieldswidget/generated/GeneratedSearchFieldWidget3.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedfieldswidget/generated/GeneratedUserDataFieldWidget3.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedfieldswidget/generated/GeneratedPasswordFieldWidget2.dart';

/* Frame Fields
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFieldsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 343.0,
      height: 290.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 56.0,
              child: GeneratedSearchFieldWidget3(),
            ),
            Positioned(
              left: 0.0,
              top: 120.0,
              right: null,
              bottom: null,
              width: 296.0,
              height: 53.0,
              child: GeneratedUserDataFieldWidget3(),
            ),
            Positioned(
              left: 0.0,
              top: 237.0,
              right: null,
              bottom: null,
              width: 296.0,
              height: 53.0,
              child: GeneratedPasswordFieldWidget2(),
            )
          ]),
    ));
  }
}
