import 'package:flutter/material.dart';
import 'package:flutterapp/figma_fluttlabapp/generatednotfoundwidget/generated/GeneratedContentWidget4.dart';
import 'package:flutterapp/figma_fluttlabapp/generatednotfoundwidget/generated/GeneratedStatusBarWidget5.dart';
import 'package:flutterapp/figma_fluttlabapp/generatednotfoundwidget/generated/GeneratedHomeBarWidget6.dart';
import 'package:flutterapp/figma_fluttlabapp/generatednotfoundwidget/generated/GeneratedPreviosButton48pxWidget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatednotfoundwidget/generated/GeneratedSearchFieldWidget1.dart';

/* Frame Not found
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNotfoundWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBarWidget5(),
              ),
              Positioned(
                left: 15.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 48.0,
                child: GeneratedPreviosButton48pxWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 124.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 56.0,
                child: GeneratedSearchFieldWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 367.0,
                child: GeneratedContentWidget4(),
              ),
              Positioned(
                left: 121.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 34.0,
                child: GeneratedHomeBarWidget6(),
              )
            ]),
      ),
    ));
  }
}
