import 'package:flutter/material.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedthumbnailwidget/generated/GeneratedCourseCardWidget9.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedthumbnailwidget/generated/GeneratedRectangleWidget14.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedthumbnailwidget/generated/GeneratedCourseCardWidget8.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedthumbnailwidget/generated/GeneratedCourseCardWidget5.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedthumbnailwidget/generated/GeneratedCoolKidsStandingWidget6.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedthumbnailwidget/generated/GeneratedCourseCardWidget7.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedthumbnailwidget/generated/GeneratedTitleWidget42.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedthumbnailwidget/generated/GeneratedBlushIconWidget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedthumbnailwidget/generated/GeneratedCoolKidsStandingWidget3.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedthumbnailwidget/generated/GeneratedCoolKidsStandingWidget4.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedthumbnailwidget/generated/GeneratedCourseCardWidget6.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedthumbnailwidget/generated/GeneratedCoolKidsStandingWidget7.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedthumbnailwidget/generated/GeneratedCoolKidsStandingWidget2.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedthumbnailwidget/generated/GeneratedCoolKidsStandingWidget5.dart';

/* Frame Thumbnail
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedThumbnailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1287.5693969726562,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1920.0,
                      height: 960.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 26, 11, 57),
                              ),
                            ),
                            Positioned(
                              left: 954.0521850585938,
                              top: 19.0,
                              right: null,
                              bottom: null,
                              width: 513.3900146484375,
                              height: 445.26861572265625,
                              child: GeneratedCourseCardWidget5(),
                            ),
                            Positioned(
                              left: 1511.33544921875,
                              top: 76.42401123046875,
                              right: null,
                              bottom: null,
                              width: 513.3900146484375,
                              height: 445.26861572265625,
                              child: GeneratedCourseCardWidget6(),
                            ),
                            Positioned(
                              left: 1163.136962890625,
                              top: 134.67535400390625,
                              right: null,
                              bottom: null,
                              width: 855.8880615234375,
                              height: 1152.89404296875,
                              child: GeneratedCoolKidsStandingWidget2(),
                            ),
                            Positioned(
                              left: -97.64901733398438,
                              top: 62.0,
                              right: null,
                              bottom: null,
                              width: 578.8335571289062,
                              height: 779.1990356445312,
                              child: GeneratedCoolKidsStandingWidget3(),
                            ),
                            Positioned(
                              left: 222.0,
                              top: 94.0,
                              right: null,
                              bottom: null,
                              width: 597.0,
                              height: 238.0,
                              child: GeneratedTitleWidget42(),
                            ),
                            Positioned(
                              left: 1421.0521240234375,
                              top: 555.0,
                              right: null,
                              bottom: null,
                              width: 513.3900146484375,
                              height: 445.26861572265625,
                              child: GeneratedCourseCardWidget7(),
                            ),
                            Positioned(
                              left: 516.0,
                              top: 372.57781982421875,
                              right: null,
                              bottom: null,
                              width: 825.084228515625,
                              height: 690.1539306640625,
                              child: GeneratedCoolKidsStandingWidget4(),
                            ),
                            Positioned(
                              left: 937.0,
                              top: 236.03416442871094,
                              right: null,
                              bottom: null,
                              width: 620.8002319335938,
                              height: 933.8878173828125,
                              child: GeneratedCoolKidsStandingWidget5(),
                            ),
                            Positioned(
                              left: 70.704345703125,
                              top: 282.08203125,
                              right: null,
                              bottom: null,
                              width: 687.7737426757812,
                              height: 794.6224365234375,
                              child: GeneratedCoolKidsStandingWidget6(),
                            ),
                            Positioned(
                              left: 740.0521850585938,
                              top: 569.0,
                              right: null,
                              bottom: null,
                              width: 513.3900146484375,
                              height: 445.26861572265625,
                              child: GeneratedCourseCardWidget8(),
                            ),
                            Positioned(
                              left: 352.0,
                              top: 474.0,
                              right: null,
                              bottom: null,
                              width: 584.0,
                              height: 674.0,
                              child: GeneratedCoolKidsStandingWidget7(),
                            ),
                            Positioned(
                              left: 53.05218505859375,
                              top: 603.0,
                              right: null,
                              bottom: null,
                              width: 513.3900146484375,
                              height: 445.26861572265625,
                              child: GeneratedCourseCardWidget9(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 704.0,
                              right: null,
                              bottom: null,
                              width: 1920.0,
                              height: 417.0,
                              child: GeneratedRectangleWidget14(),
                            ),
                            Positioned(
                              left: 1374.0,
                              top: 756.0,
                              right: null,
                              bottom: null,
                              width: 292.0,
                              height: 136.0,
                              child: GeneratedBlushIconWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
