import 'package:flutter/material.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedproductdetailwidget/generated/GeneratedContentWidget7.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedproductdetailwidget/generated/GeneratedHomeBarWidget10.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedproductdetailwidget/generated/GeneratedStatusBarWidget9.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedproductdetailwidget/generated/GeneratedHeadersWidget1.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedproductdetailwidget/generated/GeneratedButtonWidget20.dart';

/* Frame Product Detail
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProductDetailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBarWidget9(),
              ),
              Positioned(
                left: 121.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 34.0,
                child: GeneratedHomeBarWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 379.0,
                height: 585.0,
                child: GeneratedContentWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 40.0,
                child: GeneratedHeadersWidget1(),
              ),
              Positioned(
                left: 33.0,
                top: 714.0,
                right: null,
                bottom: null,
                width: 309.0,
                height: 56.0,
                child: GeneratedButtonWidget20(),
              )
            ]),
      ),
    ));
  }
}
