import 'package:flutter/material.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedtextstyleswidget/generated/GeneratedParagraphLargeWidget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedtextstyleswidget/generated/GeneratedButtonMediumWidget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedtextstyleswidget/generated/GeneratedHeadingH3Widget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedtextstyleswidget/generated/GeneratedHeadingH5Widget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedtextstyleswidget/generated/GeneratedHeadingH2Widget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedtextstyleswidget/generated/GeneratedHeadingH4Widget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedtextstyleswidget/generated/GeneratedButtonLargeWidget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedtextstyleswidget/generated/GeneratedParagraphMediumWidget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedtextstyleswidget/generated/GeneratedButtonSmallWidget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedtextstyleswidget/generated/GeneratedHeadingH1Widget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedtextstyleswidget/generated/GeneratedParagraphSmallWidget.dart';

/* Frame Text Styles
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTextStylesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 315.0,
      height: 806.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(16.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(16.0),
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 40.0,
              top: 40.0,
              right: null,
              bottom: null,
              width: 237.0,
              height: 61.0,
              child: GeneratedHeadingH1Widget(),
            ),
            Positioned(
              left: 40.0,
              top: 139.0,
              right: null,
              bottom: null,
              width: 174.0,
              height: 48.0,
              child: GeneratedHeadingH2Widget(),
            ),
            Positioned(
              left: 40.0,
              top: 225.0,
              right: null,
              bottom: null,
              width: 138.0,
              height: 44.0,
              child: GeneratedHeadingH3Widget(),
            ),
            Positioned(
              left: 40.0,
              top: 307.0,
              right: null,
              bottom: null,
              width: 111.0,
              height: 34.0,
              child: GeneratedHeadingH4Widget(),
            ),
            Positioned(
              left: 40.0,
              top: 379.0,
              right: null,
              bottom: null,
              width: 95.0,
              height: 28.0,
              child: GeneratedHeadingH5Widget(),
            ),
            Positioned(
              left: 40.0,
              top: 445.0,
              right: null,
              bottom: null,
              width: 119.0,
              height: 28.0,
              child: GeneratedParagraphLargeWidget(),
            ),
            Positioned(
              left: 40.0,
              top: 511.0,
              right: null,
              bottom: null,
              width: 125.0,
              height: 23.0,
              child: GeneratedParagraphMediumWidget(),
            ),
            Positioned(
              left: 40.0,
              top: 572.0,
              right: null,
              bottom: null,
              width: 97.0,
              height: 20.0,
              child: GeneratedParagraphSmallWidget(),
            ),
            Positioned(
              left: 40.0,
              top: 630.0,
              right: null,
              bottom: null,
              width: 112.0,
              height: 24.0,
              child: GeneratedButtonLargeWidget(),
            ),
            Positioned(
              left: 40.0,
              top: 692.0,
              right: null,
              bottom: null,
              width: 121.0,
              height: 20.0,
              child: GeneratedButtonMediumWidget(),
            ),
            Positioned(
              left: 40.0,
              top: 750.0,
              right: null,
              bottom: null,
              width: 90.0,
              height: 18.0,
              child: GeneratedButtonSmallWidget(),
            )
          ]),
    ));
  }
}
