import 'package:flutter/material.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedcourselessonwidget/generated/GeneratedHomeBarWidget16.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedcourselessonwidget/generated/GeneratedStatusBarWidget14.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedcourselessonwidget/generated/GeneratedHeadersWidget6.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedcourselessonwidget/generated/GeneratedCourseDetailsWidget1.dart';

/* Frame Course Lesson
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCourseLessonWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 697.0,
                child: GeneratedCourseDetailsWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 780.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 32.0,
                child: GeneratedHomeBarWidget16(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBarWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 40.0,
                child: GeneratedHeadersWidget6(),
              )
            ]),
      ),
    ));
  }
}
