import 'package:flutter/material.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedprofilewidget1/generated/GeneratedTabBar2ItemWidget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedprofilewidget1/generated/GeneratedProfileWidget2.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedprofilewidget1/generated/GeneratedStatusBarWidget11.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedprofilewidget1/generated/GeneratedHeadersWidget3.dart';

/* Frame Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBarWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 40.0,
                child: GeneratedHeadersWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 116.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 492.0,
                child: GeneratedProfileWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 714.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 98.0,
                child: GeneratedTabBar2ItemWidget(),
              )
            ]),
      ),
    ));
  }
}
