import 'package:flutter/material.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedsplashscreenwidget/generated/GeneratedStatusBarWidget2.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedsplashscreenwidget/generated/GeneratedHomeBarWidget3.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedsplashscreenwidget/generated/GeneratedContentWidget1.dart';

/* Frame Splash screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashscreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 326.0,
                child: GeneratedContentWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBarWidget2(),
              ),
              Positioned(
                left: 121.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 34.0,
                child: GeneratedHomeBarWidget3(),
              )
            ]),
      ),
    ));
  }
}
