import 'package:flutter/material.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedthumbnailwidget1/generated/GeneratedFrame8Widget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedthumbnailwidget1/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedthumbnailwidget1/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedthumbnailwidget1/generated/GeneratedBlushIconWidget1.dart';

/* Frame Thumbnail
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedThumbnailWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1462.7802734375,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1920.0,
                      height: 960.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 26, 11, 57),
                              ),
                            ),
                            Positioned(
                              left: 88.76226806640625,
                              top: -842.6775512695312,
                              right: null,
                              bottom: null,
                              width: 2543.383056640625,
                              height: 1890.4766845703125,
                              child: GeneratedGroup8Widget(),
                            ),
                            Positioned(
                              left: 137.13116455078125,
                              top: 602.700439453125,
                              right: null,
                              bottom: null,
                              width: 1254.9359130859375,
                              height: 860.079833984375,
                              child: GeneratedGroup9Widget(),
                            ),
                            Positioned(
                              left: 222.0,
                              top: 86.0,
                              right: null,
                              bottom: null,
                              width: 675.0,
                              height: 268.0,
                              child: GeneratedFrame8Widget(),
                            ),
                            Positioned(
                              left: 1374.0,
                              top: 756.0,
                              right: null,
                              bottom: null,
                              width: 292.0,
                              height: 136.0,
                              child: GeneratedBlushIconWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
