import 'package:flutter/material.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedcolorswidget/generated/GeneratedUtilitiesWidget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedcolorswidget/generated/GeneratedInkWidget.dart';

/* Frame Colors
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedColorsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 472.0,
      height: 224.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(16.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(16.0),
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 24.0,
              top: 24.0,
              right: null,
              bottom: null,
              width: 424.0,
              height: 72.0,
              child: GeneratedInkWidget(),
            ),
            Positioned(
              left: 24.0,
              top: 128.0,
              right: null,
              bottom: null,
              width: 424.0,
              height: 72.0,
              child: GeneratedUtilitiesWidget(),
            )
          ]),
    ));
  }
}
