import 'package:flutter/material.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedcustomizebannerwidget/generated/GeneratedCustomizeWidget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedcustomizebannerwidget/generated/GeneratedArrow1Widget.dart';

/* Instance customize-banner
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCustomizebannerWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 748.485595703125,
      height: 174.05624389648438,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 146.12881469726562,
              top: 87.02812957763672,
              right: null,
              bottom: null,
              width: 146.12881469726562,
              height: 0.0,
              child: GeneratedArrow1Widget(),
            ),
            Positioned(
              left: 146.12881469726562,
              top: 0.0,
              right: null,
              bottom: null,
              width: 602.3567504882812,
              height: 174.05624389648438,
              child: GeneratedCustomizeWidget(),
            )
          ]),
    ));
  }
}
