import 'package:flutter/material.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedcoursetestswidget/generated/GeneratedContentWidget15.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedcoursetestswidget/generated/GeneratedStatusBarWidget15.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedcoursetestswidget/generated/GeneratedHeadersWidget7.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedcoursetestswidget/generated/GeneratedTestCardsWidget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedcoursetestswidget/generated/GeneratedHomeBarWidget17.dart';

/* Frame Course Tests
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCourseTestsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 251.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 921.0,
                child: GeneratedTestCardsWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 127.0,
                child: GeneratedContentWidget15(),
              ),
              Positioned(
                left: 0.0,
                top: 780.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 32.0,
                child: GeneratedHomeBarWidget17(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBarWidget15(),
              ),
              Positioned(
                left: 0.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 40.0,
                child: GeneratedHeadersWidget7(),
              )
            ]),
      ),
    ));
  }
}
