import 'package:flutter/material.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedintro3widget/generated/GeneratedHomeBarWidget5.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedintro3widget/generated/GeneratedSmallButtonWidget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedintro3widget/generated/GeneratedButtonWidget11.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedintro3widget/generated/GeneratedStatusBarWidget4.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedintro3widget/generated/GeneratedContentWidget3.dart';

/* Frame Intro - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIntro3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 184.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 445.0,
                child: GeneratedContentWidget3(),
              ),
              Positioned(
                left: 314.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 16.0,
                child: GeneratedSmallButtonWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 706.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 56.0,
                child: GeneratedButtonWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBarWidget4(),
              ),
              Positioned(
                left: 121.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 34.0,
                child: GeneratedHomeBarWidget5(),
              )
            ]),
      ),
    ));
  }
}
