import 'package:flutter/material.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedintro1widget/generated/GeneratedSmallButtonsWidget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedintro1widget/generated/GeneratedStatusBarWidget1.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedintro1widget/generated/GeneratedContentWidget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedintro1widget/generated/GeneratedHomeBarWidget2.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedintro1widget/generated/GeneratedButtonWidget7.dart';

/* Frame Intro - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIntro1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 188.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 446.0,
                child: GeneratedContentWidget(),
              ),
              Positioned(
                left: 314.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 16.0,
                child: GeneratedSmallButtonsWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 706.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 56.0,
                child: GeneratedButtonWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBarWidget1(),
              ),
              Positioned(
                left: 121.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 34.0,
                child: GeneratedHomeBarWidget2(),
              )
            ]),
      ),
    ));
  }
}
