import 'package:flutter/material.dart';

/* Text Text
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTextWidget54 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Segment Control
''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.0499999182564872,
        fontSize: 56.0,
        fontFamily: 'Rubik',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 59, 57, 54),

        /* letterSpacing: -1.0, */
      ),
    ));
  }
}
