import 'package:flutter/material.dart';

/* UndefinedNode Headers
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHeadersWidget15 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
