import 'package:flutter/material.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedchooselessonscoursewidget/generated/GeneratedContentWidget18.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedchooselessonscoursewidget/generated/GeneratedHomeBarWidget21.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedchooselessonscoursewidget/generated/GeneratedStatusBarWidget19.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedchooselessonscoursewidget/generated/GeneratedHeadersWidget11.dart';

/* Frame Choose Lessons Course
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChooseLessonsCourseWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 752.0,
                child: GeneratedContentWidget18(),
              ),
              Positioned(
                left: 0.0,
                top: 780.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 32.0,
                child: GeneratedHomeBarWidget21(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBarWidget19(),
              ),
              Positioned(
                left: 0.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 40.0,
                child: GeneratedHeadersWidget11(),
              )
            ]),
      ),
    ));
  }
}
