import 'package:flutter/material.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedinstructionswidget/generated/GeneratedHeadingWidget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedinstructionswidget/generated/GeneratedButtonWidget29.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedinstructionswidget/generated/GeneratedProTipWidget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedinstructionswidget/generated/GeneratedListItemWidget3.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedinstructionswidget/generated/GeneratedListItemWidget.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedinstructionswidget/generated/GeneratedListItemWidget1.dart';
import 'package:flutterapp/figma_fluttlabapp/generatedinstructionswidget/generated/GeneratedListItemWidget2.dart';

/* Instance Instructions
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInstructionsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1052.508056640625,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 672.45703125,
                    height: 1052.508056640625,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(32.0),
                      border: Border.all(
                        width: 16.0,
                        color: Color.fromARGB(255, 0, 0, 0),
                      ),
                    ),
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.circular(32.0),
                            child: Container(
                              color: Color.fromARGB(255, 255, 255, 255),
                            ),
                          ),
                          Positioned(
                            left: 58.187042236328125,
                            top: 58.187042236328125,
                            right: null,
                            bottom: null,
                            width: 494.58984375,
                            height: 265.0398864746094,
                            child: GeneratedHeadingWidget(),
                          ),
                          Positioned(
                            left: 58.18705749511719,
                            top: 360.2550354003906,
                            right: null,
                            bottom: null,
                            width: 556.0829467773438,
                            height: 75.0,
                            child: GeneratedListItemWidget(),
                          ),
                          Positioned(
                            left: 58.18705749511719,
                            top: 472.28314208984375,
                            right: null,
                            bottom: null,
                            width: 556.0829467773438,
                            height: 50.0,
                            child: GeneratedListItemWidget1(),
                          ),
                          Positioned(
                            left: 58.18705749511719,
                            top: 559.311279296875,
                            right: null,
                            bottom: null,
                            width: 556.0829467773438,
                            height: 50.0,
                            child: GeneratedListItemWidget2(),
                          ),
                          Positioned(
                            left: 58.18705749511719,
                            top: 646.3394165039062,
                            right: null,
                            bottom: null,
                            width: 556.0829467773438,
                            height: 26.448654174804688,
                            child: GeneratedListItemWidget3(),
                          ),
                          Positioned(
                            left: 58.18705749511719,
                            top: 709.816162109375,
                            right: null,
                            bottom: null,
                            width: 556.0829467773438,
                            height: 192.31784057617188,
                            child: GeneratedProTipWidget(),
                          ),
                          Positioned(
                            left: 58.187042236328125,
                            top: 939.162109375,
                            right: null,
                            bottom: null,
                            width: 270.8973083496094,
                            height: 55.1589241027832,
                            child: GeneratedButtonWidget29(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
