import 'package:flutter/material.dart';

/* UndefinedNode Segment Control
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSegmentControlWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
